### ISSUE TITLE
Add sorting algorithm in any language

### ISSUE THREAD

**Issue by Bijay555** [Bijay555/Hacktoberfest-Algorithms#3]
- [ ] Code should be of graph related.

- [ ] Code should be clean and well commented

- [ ]  File should be in the format mentioned in README.md and your name should be their in the comment at the beginning

**Comment by lara-sahoo** [comment]
Hey I would like to work on this. Can you  assign it to me?

**Comment by AnushkaThakkar** [comment]
Hey @Bijay555 ,
I want to contribute to this Issue
I want to add a Merge Sort Algorithm using Python.
Can I?

**Comment by webmidas** [comment]
please assign bucket sort in python to me

**Comment by sejalrastogi** [comment]
Please assign me the bubble sort in Java.

**Comment by Bijay555** [comment]
Guys @AnushkaThakkar @webmidas @sejalrastogi @lara-sahoo start contributing and send me PR request. Remember you should follow some rules defined in README.md

**Comment by arpita2712** [comment]
May I create a PR for selection sort in java

**Comment by rachitmanas** [comment]
Hi @Bijay555 .
I just made a PR concerning this issue. Please have a look and let me know if something's wrong.
Thanks!

**Comment by potyoma** [comment]
Hi. I want to add a quick sort algorithm in C#. May I?

**Comment by Bijay555** [comment]
Guys You can keep adding algorithms in any language. Make sure you dont repeat
